baseurl:
title: john-hearn.info
subtitle: Science, software and sustainability
author: John Hearn
simple_search: http://google.com/search
description: A Jekyll theme for content-rich sites
name: john-hearn
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:title
timezone: Europe/Madrid
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/clayh53.github.com/

twitter_username: johnhearnbcn
github_username: johnhearn
linkedin_username: john-hearn-599762b
