baseurl:
title: john-hearn.info
subtitle: Science and software
author: John Hearn
simple_search: http://google.com/search
description: Personal site for blogging and about science, software and such
name: john-hearn
#avatar: /assets/images/complexity/class4.png
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:title
timezone: Europe/Madrid
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/clayh53.github.com/
plugins:
  - jekyll-time-to-read
  - jekyll/graphviz

twitter_username: johnhearnbcn
github_username: johnhearn
linkedin_username: john-hearn-599762b

graphviz:
  options: "-Tsvg" # command option
  executable: "circo"   # execute this string. specify full path to 'dot' if you need